### ISSUE TITLE
The requester FAQ is not easy for them to find

### ISSUE THREAD

**Issue by markwhiting** [crowdresearch/collective#20]
Requesters on daemo often have questions about how to do things. We created an FAQ to help them find answers to there common questions, however, we don't link provide them with a way to find the FAQ in the context of their normal use of the platform.

## My proposal
I propose adding the `?` icon (which is Material Design's help icon) in a number of key locations, linking to the [FAQ](https://forum.daemo.org/t/requester-faq/321). Below are some choice locations for linking.

1. heading of the authoring page - to left of `eye` icon.
2. bottom of the authoring page - to left of `publish` button
3. projects page - between `+ create project` and `gear` icon
4. results page - to the right of the `view designs` button

---
**Use comments to share your response** or use emoji 👍 to show your support. **To officially join in**, add yourself as an assignee to the proposal. **To break consensus**, comment using [this template](https://raw.githubusercontent.com/crowdresearch/collective/master/docs/breaking_consensus). To find out more about this process, read the [how-to](https://github.com/crowdresearch/collective/blob/master/docs/CONTRIBUTING.md).

**Comment by mbernst** [comment]
Some ideas!

> heading of the authoring page - to left of eye icon.

Help is often in the top right, so I would suggest moving this to the right of the trash can.

> bottom of the authoring page - to left of publish button

This is sort of counter-norm for design. Given that the one on the top will be sticky and stay on the page no matter where you scroll, I'd advocate not including it here.

> projects page - between + create project and gear icon

Works for me

> results page - to the right of the view designs button

Here I assume it would look like the other buttons and say "Help"

**Comment by markwhiting** [comment]
I agree with these points. Thanks.
