### ISSUE TITLE
[Update] Progress tags for academic paper and conference projects in the group

### ISSUE THREAD

**Issue by qwertyone** [crowdresearch/collective#37]
## Problem
It can be a challenge for a large group of people to succeed in publishing papers and completing presentations within the crowdwork setting. This proposal is intended to clarify what labels in github should be introduced and how it might be possible to track changes in Works In Process to avoid unnecessary confusions and speed the collective's members to scan through daemo's web sites.

Currently there is not a context specific tagging system (labels) to support teams to move through the research process, yet there is one for the constitutional amendment process. 
## Proposal
A system of identified keywords for the group to support updates within the research context to serve through keyword tags. The tags might appear as labels for github, most likely.
## Short Term Implications
The agreement of research context landmarks needs to be in agreement, an example is provided below. As such a small group (3 to 4) with successful proposals from CRG can be asked their own research processes, generally, and then responses collected. The tags would targeted for appropriate placement within the Daemo system.

## Long Term Implications
As such, a research oriented label system would enable members to identify where an effort is and the researchers of daemo to more cleanly monitor and analyze the usage of the tags to provide updates and know the progress of past efforts.  For those on-boarding, the tags begin a process of rapid knowledge acquisition of the group and how it works. It will serve as a map to speed up their involvement and shorten the learning curve of the group.

**Comment by qwertyone** [comment]
For the research path of the Collective, the following status tags are proposed in order of sequence:

- In Discussion (to describe more solid ideas with crowd push)
- In Proposal
- Proposed (background and proposal statements written, awaiting vote)
- In Voting (result being passed, failed and related outcome)

Conditional tags if passed:
- In Literature Review
- Initial Lit Review Complete
- In Method Development
- Method Complete
- In Study Execution
- Study Complete
- In Data Analysis
- Analysis Complete
- In Paper Synthesis and Drafting
- In Draft Revision
- Paper Submitted

Proposed tags for this process end as the study's DRI becomes the liaison between the group and the submission organization. This person as a DRI of a study is expected, not required, to update the group on the submission's final step.

**Comment by markwhiting** [comment]
The first set of tags (in discussion, in proposal, proposed and voting) seem to overlap with our existing process. Do you think these could be done with what we have, instead of adding new ones? Or alternatively, do you think these are strictly better and should replace what we have? In that case other conditions might need to be included to support things like broken consensus. 

In the second set of tags, more focused on paper writing, this seems to assume a very reliable set of steps and does not support potential alternative approaches to conducting research. I wonder if this could be formalized as a series of proposals that work together to make a research project successful, as opposed to many tags that may be more likely to confuse our use than facilitating improved performance. What are your thoughts on something like that?

**Comment by qwertyone** [comment]
![image](https://user-images.githubusercontent.com/6076358/34322143-cdc7fa7e-e81f-11e7-8545-e0bbd7cc9cd2.png)

This is the only tag system I know, which is governance and programming.  Adding the proposed tags to this would create an undue and bothersome scrolling and might make the github, this one, unduly complicated. So I don't know if the current system as is might handle this.

I do not think that these tags are better, yet I would encourage more knowledgeable members to eliminate and redefine them. This is mentioned in the short term implications.

For your point regarding the second set of tags, I am seeking the most generic ones. Discussion, Lit reviews, Analysis, Synthesis, Submission as tags are fairly generic and I would think support the group in the way I hope, monitoring as a main function. How might you formalize this differently? My imagination escapes me on this question.

**Comment by mbernst** [comment]
I was imagining that research might proceed through proposals, perhaps with GitHub milestones attached (e.g., CSCW 2018) so we can separate out individual research threads. I'm open to alternatives. My initial inclination is to play with these things informally before formalizing a process in a proposal?

**Comment by qwertyone** [comment]
Let's mark this proposal for later and follow up in a few months on this topic. How do we properly close an issue and mark it to arise later?

**Comment by markwhiting** [comment]
@qwertyone Nobody has assigned themselves to this. Proposals with no assignees should be closed and can be reopened when someone is willing to take them forward. If this was a mistake, i.e. you intended to assign yourself, please fix it for the next consensus period. If this was not a mistake, feel free to close this yourself.

**Comment by qwertyone** [comment]
![image](https://user-images.githubusercontent.com/6076358/34417070-d1847a18-ebf6-11e7-95db-a856775f9068.png)

This is closed for another time.
