### ISSUE TITLE
Formalization of the current quality review teams.

### ISSUE THREAD

**Issue by qwertyone** [crowdresearch/collective#44]
## Problem and Question
The design quality group seems to handle many functions and it should.  Is it necessary to topically subset the quality review group this early when the actual work demands are unknown? Would it be preferential to let the work demands split the group?

I anticipate that the separation of the quality design group by topic without the knowledge of the actual work demand this early might create a specialization that will bias action and decision making towards that given topic without proper merit -- UX, IxD, Survey Design, Information Architecture are all potentially alternative groups which might arise. As this is the potential case, I would propose that this division of labor is postponed until at which some time when the work demands require the benefits of specialization. The diversion of resources and responsibilities being taken from the main Quality Design Review group too early might compromise and complicate the real needs of the group. The specialization might be better merited when 5 or more projects arise concurrently whereby the specialist domain knowledge might serve to speed the quality review process. To address the populating of members into the groups, I would encourage that the previous nominations stand but instead fall under the more general quality review team which contains no separation by topic (leadership team).

## Proposal
For this proposal, I am seeking a brief one week discussion on the necessary groups based from past experiences (those identified at https://github.com/crowdresearch/collective/blob/master/governance/groups.md), what justifies these groups creation and disbanding in the spirit of keeping the groups creative (i.e. during slow times), a clearly articulated mission or problem focus for each creative problem solving group, expected membership size, expected meeting frequency, the DRI for the specific group (it is normal practice for a group leader), brief training into either Parnes-Noeller Creative Problem Solving, PDCA (plan, do, check, act) or DMAIC (define, measure, analyze, improve, control) or DMADV (define, measure, analyze, design, verify) as related to the problem, the selection of members by expertise, and that the creation of such teams originate from a more general team. @dmorina and @neilthemathguy might be able to elaborate the SCRUM problem solving methods that might be more appropriate here.

## Implications
This proposal seeks the following things: 1) to arrest the topically defined splintering of the quality review teams and to maintain the cross functional expertise found within the membership of the group accompanied by either a specific problem solving statement, SMART goal, or issue related process as we seem to be developing organically, 2) align the groups processes with those found within industry (a big bonus for recruiting) and 3) it would help to flush out the successful practices of the research group that have resulted in a successful platform and publications in high quality conferences within a highly distributed and diverse work group.

In the long term, this proposal will help to clarify for its membership the practices that need to be introduced more formally for on-boarding and when the above problem solving methods are used to great effect.

---
**Use comments to share your response** or use emoji 👍 to show your support. **To officially join in**, add yourself as an assignee to the proposal. **To break consensus**, comment using [this template](https://raw.githubusercontent.com/crowdresearch/collective/master/docs/breaking_consensus). To find out more about this process, read the [how-to](https://github.com/crowdresearch/collective/blob/master/docs/CONTRIBUTING.md).

**Comment by qwertyone** [comment]
![image](https://user-images.githubusercontent.com/6076358/34479679-76cdd47e-efa8-11e7-8f0d-0e154c51241b.png)

**Comment by iceLearn** [comment]
With all do respect, I do not understand a single thing in this project proposal. ;) 

Help me to understand - what are you trying to solve - as I can assume, you are thinking Design quality review team as one whole team thing, and requesting it to break based on the demand? 

Or are you proposing one group of team who will be looking after each project and based on the skills they will be allocating to other groups?

Anyway need more explanations.

**Comment by qwertyone** [comment]
## Response
That is alright. I come from an educational background that has a manufacturing focus, upon which the quality was a topic in many of my courses. When I elaborate, you will see that some of the behaviors taught by Bernstein are influenced by the word of Osborne, Parnes and Noeller. The other stuff is industrial engineering and managerial consulting influenced. I suspect by introducing, at this time, the language or how this stuff is structured, we might be able to originate something for the larger group. This as an aside, though.

The main proposal, as I understand it and how it is turning out, is to define teams that review the work happening within the group, which I agree with. However the design of teams may impact the work of the group unintentionally. For example, the language I have introduced, DMAIC, PCDA, etc... are jargony, but I have a good understanding of them. When I write Measure from DMAIC, I create the conditions for those familiar to run with the methods of Measure, which saves time in coordination and lessens potential conflicts in understanding. For others, they must learn and slow down the conversations and action. The nominations will have this purpose, and right now the decision facing the group is how to structure these core teams -- are they cross-functional or specialized within a topic? When more people are on a team with a certain background, their methods will be shaped by what they know, as well as the projects selected and performed. A fish will always swim under water whereas an otter skirts along the top the most of the time. I am trying to keep the fish and otters together so that the combinations of their eyes can determine if the proposals from the incoming cohort need the specialization or more creative/collaborative solutions.

From my experience and readings in quality engineering, the main quality review teams should be cross functional and driven by the 'issue' at hand. Is the issue really an issue from the perspectives of individual team members? Take this proposal. If I had my own team, we might just run with it and the jargon might seem right because it is jargony. The chances for group think increase. Meanwhile, another person from another background might 'break consensus' more readily or be able to ask the questions that only their lack of shared background can only provide.

This is my frame of reference.

## Minimum Proposal
The barest proposal is keep the User Researcher nominations within the design quality review team. Let this larger team diverge and converge based from the issues presented and the act upon them as discussed. A functionally driven and expertise selection originates from this. There might be an automatic breaking point if an active collective of 500 people typed out 15 proposals focused on User Research. The review of the proposals might be best served this way.

## The add-ons might be:
-  an awareness of generic processes to ease the communication between the cross functional nature of this proposal. (i.e. for this group's governance, 'observe, propose, deliberate, vote' might simplify the interactions of people in a way similar to DMAIC works for Six Sigma teams)
- the specification of what these teams control (project support and selection are basic ones I can foresee) 
- a regular meeting time for these teams (ie frequency of contacts can maintain relationships)

Please keep the questions coming. It helps me to work better with the team.

**Comment by neilthemathguy** [comment]
@qwertyone Very thoughtful and well written proposal!

**Comment by shirishgoyal** [comment]
@qwertyone Just trying to understand the rationale for tagging it as urgent - Is it because of the nominations for User Research QR group which are already in progress? OR you think User Research teams' scope should be clearly defined first (which I strongly agree) to proceed with nominations?

**Comment by qwertyone** [comment]
Oh... This is an error. I thought I removed it after the label creation.

**Comment by qwertyone** [comment]
> 'you think User Research teams' scope should be clearly defined first (which I strongly agree) to proceed with nominations?'

@shirishgoyal The clear scoping of teams is important, so I would like to see it at some point. It would be nice to read the scoping provided by the members so that the abilities and expertise of the nominees drive them and we manage scope creep.

@iceLearn

**Comment by iceLearn** [comment]
I don't know how easy to set up scope to each group such as user research group, we can easily define job role and expectation.  However, I really do agree on you @qwertyone on the cross functional collaboration to optimize the quality review. I think is will work based on mutual understanding and since we all will work towards the good faith of this project. 

Anyway @qwertyone  could you be more explicit on outcome of the proposal, I am not sure what changes you introduce?

**Comment by qwertyone** [comment]
> The barest proposal is keep the User Researcher nominations within the design quality review team. Let this larger team diverge and converge based from the issues presented and the act upon them as discussed. A functionally driven and expertise selection originates from this. There might be an automatic breaking point if an active collective of 500 people typed out 15 proposals focused on User Research. The review of the proposals might be best served this way.

The immediate implications are not to isolate the UX group on the organizational chart, during meetings of the design quality review group that nature of the problem as presented and then the nature of the problem as discussed lead to the selection of proposals and the responses to those proposals, that the expected functions are made clear, current expertise known (not all UXer's have a stats background), and so on.

Scoping would refer to goals, deliverables, functions, and tasks associated with each group. Developing and sharing the priority user stories to the group for examples as well as saying that a proposal needs to consider best this use case... Arguably, because UX is a research based group, they might be the major group task with review of the statistical methods or the methods proposed before the group...

**Comment by mbernst** [comment]
My suggestion is to maintain a UX research group and UI design group
because this is common industry practice: UX research studies user behavior
on the system, and UI designers focus on how to create new designs based on
that understanding. While many individuals can have both skillsets, I don't
think we need to assume both. These two groups are often the two largest
groups in the companies I've seen (e.g., Google, Facebook). I don't think
it is too fine grained a distinction. Here's an example describing them:
https://www.fastcodesign.com/3032719/ui-ux-who-does-what-a-designers-guide-to-the-tech-industry

**Comment by qwertyone** [comment]
Design
--Ux
--UI

“Define interaction models, user task flows, and UI specifications. Communicate scenarios, end-to-end experiences, interaction models, and screen designs to stakeholders. Work with our creative director and visual designers to incorporate the visual identity of ... into features. Develop and maintain design wireframes, mockups, and specifications as needed.”

Deliverables: Wireframes of screens, storyboards, sitemap

Tools of the trade: Photoshop, Sketch, Illustrator, Fireworks, InVision....

Well... This was not too hard of a proposal. @iceLearn Please review the article and let's begin the process of flushing it out for the group.

**Comment by qwertyone** [comment]
The starting document to begin clarification is here: https://docs.google.com/document/d/1AL4jzP3JqtEdpnV-yHyhz4427GUbs6RV5FCgxF8r7lQ/edit?usp=sharing

I will invite people to edit directly soon, only commenting has been enabled.

**Comment by qwertyone** [comment]
Closed -- discussion moving to #50
