### ISSUE TITLE
The website is down

### ISSUE THREAD

**Issue by Speldosa** [crowdresearch/collective#58]
The website [is down](https://downforeveryoneorjustme.com/http://crowdresearch.stanford.edu).

## My proposal
I don't know how to fix this.

---
**Use comments to share your response** or use emoji 👍 to show your support. **To officially join in**, add yourself as an assignee to the proposal. **To break consensus**, comment using [this template](https://raw.githubusercontent.com/crowdresearch/collective/master/docs/breaking_consensus). To find out more about this process, read the [how-to](https://github.com/crowdresearch/collective/blob/master/docs/CONTRIBUTING.md).

**Comment by markwhiting** [comment]
Back up. Thanks!
