### ISSUE TITLE
Disable edu and org discount for now

### ISSUE THREAD

**Issue by mbernst** [crowdresearch/collective#59]
The purpose of the `.edu` and `.org` discount via my Sloan Fellowship funds was to encourage new requesters. However, right now it is overwhelmingly being used by a single researcher here at Stanford, to the tune of many thousand dollars already. We are effectively subsidizing a single research project, rather than encouraging new requesters.

## My proposal
Ideally I would suggest that we cap the discount per account. However, Durim suggests that this is not currently a readily executable technical option, and that the most feasible fix would be to disable the discount.

So, let's disable the discount until such time as we have the bandwidth to implement a per-account cap. Otherwise this is quickly spending out the funding in a way that was not intended.

The short-term implication is that costs will double for the currently discounted requesters. However, we are talking about only one requester right now, and even after doubling their fee, we still offer a better service than Amazon Mechanical Turk due to no other platform fees. We will also need to communicate this change to him, which I am happy to do, and remove the homepage wording about the discount.

The long-term implication is that there may be more overhead if future requesters appear and we want to re-enable a per-account `.edu` or `.org` discount, as we will need to figure out a solution.

---
**Use comments to share your response** or use emoji 👍 to show your support. **To officially join in**, add yourself as an assignee to the proposal. **To break consensus**, comment using [this template](https://raw.githubusercontent.com/crowdresearch/collective/master/docs/breaking_consensus). To find out more about this process, read the [how-to](https://github.com/crowdresearch/collective/blob/master/docs/CONTRIBUTING.md).

**Comment by markwhiting** [comment]
I've checked this and am now closing it because its complete.

In summary, settings were adjusted to stop the discount, language on the website was adjusted in https://github.com/crowdresearch/daemo/pull/1049 and the existing requester mentioned above was informed of the change.
